export const category = [
  {
    id: 0,
    name: "Chicken",
    coverImage: "images/chicken.jpg",
    title: "Fresh and high-quality chicken cuts.",
    products: [
      {
        id: 0,
        image: "images/chicken.jpg",
        name: "Boneless Chicken Breast",
        description: "Taste your favourite delicious Chicken",
        price: 660,
      },
      {
        id: 1,
        name: "Chicken Wings",
        image: "images/chicken.jpg",
        description: "Taste your favourite delicious Chicken",
        price: 680,
      },
      {
        id: 2,
        name: "Chicken Leg Quarters",
        image: "images/chicken.jpg",
        description: "Taste your favourite delicious Chicken",
        price: 600,
      },
      {
        id: 3,
        name: "Chicken Breast Fillets",
        image: "images/chicken.jpg",
        description: "Taste your favourite delicious Chicken",
        price: 400,
      },
      {
        id: 4,
        name: "Whole Chicken",
        image: "images/chicken.jpg",
        description: "Taste your favourite delicious Chicken",
        price: 390,
      },
    ],
    similar_prod: [
      {
        id: 0,
        image: "/images/chicken.jpg",
        name: "Boneless Chicken Breast",
        description: "Taste your favourite delicious Chicken",
        price: 660,
      },
      {
        id: 1,
        name: "Chicken Wings",
        image: "/images/chicken.jpg",
        description: "Taste your favourite delicious Chicken",
        price: 680,
      },
      {
        id: 2,
        name: "Chicken Leg Quarters",
        image: "/images/chicken.jpg",
        description: "Taste your favourite delicious Chicken",
        price: 600,
      },
      {
        id: 3,
        name: "Chicken Leg Quarters",
        image: "/images/chicken.jpg",
        description: "Taste your favourite delicious Chicken",
        price: 600,
      },
      {
        id: 4,
        name: "Chicken Leg Quarters",
        image: "/images/chicken.jpg",
        description: "Taste your favourite delicious Chicken",
        price: 600,
      },
      {
        id: 5,
        name: "Chicken Leg Quarters",
        image: "/images/chicken.jpg",
        description: "Taste your favourite delicious Chicken",
        price: 600,
      },
    ],
  },
  {
    id: 1,
    name: "Mutton",
    coverImage: "images/mutton.jpg",
    title: "Tender mutton cuts for various dishes.",
    products: [
      {
        id: 5,
        name: "Mutton Chops",
        image: "images/mutton.jpg",
        description: "Taste your favourite delicious Mutton",
        price: 860,
      },
      {
        id: 6,
        name: "Mutton Leg Pieces",
        image: "images/mutton.jpg",
        description: "Taste your favourite delicious Mutton",
        price: 480,
      },
      {
        id: 7,
        name: "Minced Mutton",
        image: "images/mutton.jpg",
        description: "Taste your favourite delicious Mutton",
        price: 900,
      },
      {
        id: 8,
        name: "Mutton Ribs",
        image: "images/mutton.jpg",
        description: "Taste your favourite delicious Mutton",
        price: 650,
      },
    ],
    similar_prod: [
      {
        id: 0,
        name: "Mutton Chops",
        image: "/images/mutton.jpg",
        description: "Taste your favourite delicious Mutton",
        price: 860,
      },
      {
        id: 1,
        name: "Mutton Leg Pieces",
        image: "/images/mutton.jpg",
        description: "Taste your favourite delicious Mutton",
        price: 480,
      },
      {
        id: 2,
        name: "Minced Mutton",
        image: "/images/mutton.jpg",
        description: "Taste your favourite delicious Mutton",
        price: 900,
      },
    ],
  },
  {
    id: 2,
    name: "Fish",
    coverImage: "images/fish.jpg",
    title: "A variety of fresh fish options.",
    products: [
      {
        id: 9,
        name: "Salmon Fillets",
        image: "images/fish.jpg",
        description: "Taste your favourite delicious Fish",
        price: 1250,
      },
      {
        id: 10,
        name: "Whole Tuna",
        image: "images/fish.jpg",
        description: "Taste your favourite delicious Fish",
        price: 850,
      },
      {
        id: 11,
        name: "Cod Steaks",
        image: "images/fish.jpg",
        description: "Taste your favourite delicious Fish",
        price: 580,
      },
      {
        id: 12,
        name: "Fish Chunks",
        image: "images/fish.jpg",
        description: "Taste your favourite delicious Fish",
        price: 600,
      },
      {
        id: 13,
        name: "Smoked Salmon",
        image: "images/fish.jpg",
        description: "Taste your favourite delicious Fish",
        price: 390,
      },
    ],
    similar_prod: [
      {
        id: 0,
        name: "Salmon Fillets",
        image: "/images/fish.jpg",
        description: "Taste your favourite delicious Fish",
        price: 1250,
      },
      {
        id: 1,
        name: "Whole Tuna",
        image: "/images/fish.jpg",
        description: "Taste your favourite delicious Fish",
        price: 850,
      },
      {
        id: 2,
        name: "Cod Steaks",
        image: "/images/fish.jpg",
        description: "Taste your favourite delicious Fish",
        price: 580,
      },
    ],
  },
  {
    id: 3,
    name: "Eggs",
    coverImage: "images/egg.jpg",
    title: "Fresh eggs from local farms.",
    products: [
      {
        id: 14,
        name: "Farm Fresh Chicken Eggs",
        image: "images/egg.jpg",
        description: "Taste your favourite delicious Eggs",
        price: 157,
      },
      {
        id: 15,
        name: "Large Duck Eggs",
        image: "images/egg.jpg",
        description: "Taste your favourite delicious Eggs",
        price: 144,
      },
      {
        id: 16,
        name: "Delicate Quail Eggs ",
        image: "images/egg.jpg",
        description: "Taste your favourite delicious Eggs",
        price: 168,
      },
      {
        id: 17,
        name: "Brown Eggs",
        image: "images/egg.jpg",
        description: "Taste your favourite delicious Eggs",
        price: 360,
      },
    ],
    similar_prod: [
      {
        id: 0,
        name: "Farm Fresh Chicken Eggs",
        image: "/images/egg.jpg",
        description: "Taste your favourite delicious Eggs",
        price: 157,
      },
      {
        id: 1,
        name: "Large Duck Eggs",
        image: "/images/egg.jpg",
        description: "Taste your favourite delicious Eggs",
        price: 144,
      },
      {
        id: 2,
        name: "Delicate Quail Eggs ",
        image: "/images/egg.jpg",
        description: "Taste your favourite delicious Eggs",
        price: 168,
      },
    ],
  },
];
